## FLIGHT PRICE PREDICTION
Anyone who has booked a flight ticket knows how unexpectedly the prices vary. The cheapest available ticket on a given flight gets more and less expensive over time. This usually happens as an attempt to maximize revenue based on -

Time of purchase patterns (making sure last-minute purchases are expensive)
Keeping the flight as full as they want it (raising prices on a flight which is filling up in order to reduce sales and hold back inventory for those expensive last-minute expensive purchases) So, you have to work on a project where you collect data of flight fares with other features and work to make a model to predict fares of flights.
## STEPS
## 1. Data Collection
You have to scrape at least 1500 rows of data. You can scrape more data as well, it’s up to you, More the data better the model In this section you have to scrape the data of flights from different websites (yatra.com, skyscanner.com, official websites of airlines, etc). The number of columns for data doesn’t have limit, it’s up to you and your creativity. Generally, these columns areairline name, date of journey, source, destination, route, departure time, arrival time, duration, total stops and the target variable price. You can make changes to it, you can add or you can remove some columns, it completely depends on the website from which you are fetching the data.

##### COLUMNS:
##### airline name, date of journey, source, destination, route, departure time, arrival time, duration, total stops and the target variable price

In [1]:
import pandas as pd
import selenium
from selenium import webdriver
import time

import warnings
warnings.filterwarnings('ignore')

In [53]:
Airline_name = []
Date = []
arrival_time=[]
dep_time = []
source = []
destination=[]
duration = []
total_stops = []
price=[]

In [54]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=BOM&destinationCountry=IN&flexi=0&flight_depart_date=22%2F03%2F2022&hb=&noOfSegments=1&origin=DEL&originCountry=IN&type=O&unique=1647710414601&viewName=normal')
time.sleep(2)

In [55]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[1]/div/div[2]/span')
    for i in tag:
        Airline_name.append(i.text)
        
    l1 = len(Airline_name)
    length=l1
except:
    Airline_name.append('Nan')
    
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
        
except:
    pass

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')
    
len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25)

In [58]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=BOM&destinationCountry=IN&flexi=0&flight_depart_date=25%2F03%2F2022&hb=&noOfSegments=1&origin=DEL&originCountry=IN&type=O&unique=1647711384279&viewName=normal')
time.sleep(2)

In [59]:
for i in range(1000):
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")

In [60]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[1]/div/div[2]/span')
    for i in tag:
        Airline_name.append(i.text)
        
    l2 = len(Airline_name)-l1
    length=l2
except:
    Airline_name.append('Nan')
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
        
except:
    pass

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')
    
len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60)

In [61]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=BOM&destinationCountry=IN&flexi=0&flight_depart_date=26%2F03%2F2022&hb=&noOfSegments=1&origin=DEL&originCountry=IN&type=O&unique=1647711384279&viewName=normal')
time.sleep(2)

In [62]:
for i in range(500):
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")

In [63]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[1]/div/div[2]/span')
    for i in tag:
        Airline_name.append(i.text)
        
    l3 = len(Airline_name)-l2-l1
    length=l3
except:
    Airline_name.append('Nan')
    
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
        
except:
    pass

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')
    
len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95)

In [64]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=BOM&destinationCountry=IN&flexi=0&flight_depart_date=23%2F03%2F2022&hb=&noOfSegments=1&origin=DEL&originCountry=IN&type=O&unique=1647711384279&viewName=normal')
time.sleep(2)

In [65]:
for i in range(500):
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")

In [66]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[1]/div/div[2]/span')
    for i in tag:
        Airline_name.append(i.text)
        
    l4 = len(Airline_name)-l1-l2-l3
    length=l4
except:
    Airline_name.append('Nan')
    
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
        
except:
    pass

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')
    
len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(130, 130, 130, 130, 130, 130, 130, 130, 130, 130, 130)

In [67]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=BOM&destinationCountry=IN&flexi=0&flight_depart_date=24%2F03%2F2022&hb=&noOfSegments=1&origin=DEL&originCountry=IN&type=O&unique=1647711384279&viewName=normal')
time.sleep(2)

In [68]:
for i in range(100):
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")

In [69]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[1]/div/div[2]/span')
    for i in tag:
        Airline_name.append(i.text)
        
    l5 = len(Airline_name)-l1-l2-l3-l4
    length=l5
except:
    Airline_name.append('Nan')
    
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
        
except:
    pass

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')
    
len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(165, 165, 165, 165, 165, 165, 165, 165, 165, 165, 165)

In [71]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=BOM&destinationCountry=IN&flexi=0&flight_depart_date=02%2F04%2F2022&hb=&noOfSegments=1&origin=DEL&originCountry=IN&type=O&unique=1647711384279&viewName=normal')
time.sleep(2)

In [72]:
for i in range(500):
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")

In [73]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[1]/div/div[2]/span')
    for i in tag:
        Airline_name.append(i.text)
        
    l6 = len(Airline_name)-l1-l2-l3-l4-l5
    length=l6
except:
    Airline_name.append('Nan')
    
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
        
except:
    pass

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')
    
len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time), len(source),len(destination),len(duration),len(price)

(200, 200, 200, 200, 200, 200, 200, 200, 200)

In [74]:
df1 = pd.DataFrame({'Airline Name':Airline_name, 'Departure Date':Date,'Arrival Time':arrival_time,'Departure Time':dep_time, 'Source':source, 'Destination':destination,'Duration':duration,'Total Stops':total_stops,'Price':price})
df1

,Airline Name,Departure Date,Arrival Time,Departure Time,Source,Destination,Duration,Total Stops,Price
0,Go First,"Wed, 23 Mar",17:00,15:00,New Delhi,Mumbai,2h 00m,Non Stop,"7,320"
1,Air India,"Wed, 23 Mar",20:00,18:00,New Delhi,Mumbai,2h 00m,Non Stop,"7,320"
2,IndiGo,"Wed, 23 Mar",04:10,02:00,New Delhi,Mumbai,2h 10m,Non Stop,"7,320"
3,Go First,"Wed, 23 Mar",13:25,11:15,New Delhi,Mumbai,2h 10m,Non Stop,"7,320"
4,IndiGo,"Wed, 23 Mar",19:25,17:15,New Delhi,Mumbai,2h 10m,Non Stop,"7,320"
...,...,...,...,...,...,...,...,...,...
195,Vistara,,09:45,07:30,New Delhi,Mumbai,2h 15m,Non Stop,"7,320"
196,Go First,,10:15,08:00,New Delhi,Mumbai,2h 15m,Non Stop,"7,320"
197,IndiGo,,11:00,08:45,New Delhi,Mumbai,2h 15m,Non Stop,"7,320"
198,Air India,,11:15,09:00,New Delhi,Mumbai,2h 15m,Non Stop,"7,320"
199,Vistara,,12:35,10:20,New Delhi,Mumbai,2h 15m,Non Stop,"7,320"

## Delhi - Banglore

In [75]:
Airline_name = []
Date = []
arrival_time=[]
dep_time = []
source = []
destination=[]
duration = []
total_stops = []
price=[]

In [76]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=BLR&destinationCountry=IN&flexi=0&flight_depart_date=02%2F04%2F2022&hb=0&noOfSegments=1&origin=DEL&originCountry=IN&type=O&unique=1647718969898&viewName=normal')
time.sleep(2)

In [77]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//div/div/div/div[2]/div[1]/div/div[2]/span')
    for i in tag:
        Airline_name.append(i.text)
        
    l1 = len(Airline_name)
    length= l1
except:
    Airline_name.append('Nan')
    
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
except:
    Date.append('Nan')

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')
    
len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25)

In [78]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=BLR&destinationCountry=IN&flexi=0&flight_depart_date=04%2F04%2F2022&hb=0&noOfSegments=1&origin=DEL&originCountry=IN&type=O&unique=1647718969898&viewName=normal')
time.sleep(2)

In [79]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[1]/div/div[2]/span')
    for i in tag:
        Airline_name.append(i.text)
        
    l2 = len(Airline_name)-l1
    length=l2
except:
    Airline_name.append('Nan')
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
        
except:
    pass

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')
    
len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50)

In [80]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=BLR&destinationCountry=IN&flexi=0&flight_depart_date=06%2F04%2F2022&hb=0&noOfSegments=1&origin=DEL&originCountry=IN&type=O&unique=1647718969898&viewName=normal')
time.sleep(2)

In [81]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[1]/div/div[2]/span')
    for i in tag:
        Airline_name.append(i.text)
        
    l3 = len(Airline_name)-l2-l1
    length=l3
except:
    Airline_name.append('Nan')
    
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
        
except:
    pass

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')
    
len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75)

In [82]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=BLR&destinationCountry=IN&flexi=0&flight_depart_date=23%2F03%2F2022&hb=0&noOfSegments=1&origin=DEL&originCountry=IN&type=O&unique=1647718969898&viewName=normal')
time.sleep(2)

In [83]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[1]/div/div[2]/span')
    for i in tag:
        Airline_name.append(i.text)
        
    l4 = len(Airline_name)-l1-l2-l3
    length=l4
except:
    Airline_name.append('Nan')
    
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
        
except:
    pass

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')
    
len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100)

In [84]:
df2 = pd.DataFrame({'Airline Name':Airline_name, 'Departure Date':Date,'Arrival Time':arrival_time,'Departure Time':dep_time, 'Source':source, 'Destination':destination,'Duration':duration,'Total Stops':total_stops,'Price':price})
df2

,Airline Name,Departure Date,Arrival Time,Departure Time,Source,Destination,Duration,Total Stops,Price
0,Air Asia,,10:40,08:10,New Delhi,Bangalore,2h 30m,Non Stop,"8,160"
1,Go First,,08:35,06:00,New Delhi,Bangalore,2h 35m,Non Stop,"8,160"
2,IndiGo,,11:00,08:20,New Delhi,Bangalore,2h 40m,Non Stop,"8,160"
3,Go First,,23:10,20:30,New Delhi,Bangalore,2h 40m,Non Stop,"8,160"
4,Vistara,,23:20,20:40,New Delhi,Bangalore,2h 40m,Non Stop,"8,160"
...,...,...,...,...,...,...,...,...,...
95,Go First,"Wed, 23 Mar",07:40,02:00,New Delhi,Bangalore,5h 40m,1 Stop,"8,160"
96,SpiceJet,"Wed, 23 Mar",22:45,17:00,New Delhi,Bangalore,5h 45m,1 Stop,"8,160"
97,Go First,"Wed, 23 Mar",14:55,09:00,New Delhi,Bangalore,5h 55m,1 Stop,"8,160"
98,Go First,"Wed, 23 Mar",11:50,05:50,New Delhi,Bangalore,6h 00m,1 Stop,"8,160"
99,Go First,"Wed, 23 Mar",00:20\n+ 1 day,18:20,New Delhi,Bangalore,6h 00m,1 Stop,"8,160"

## Mumbai-Bangalore

In [85]:
Airline_name = []
Date = []
arrival_time=[]
dep_time = []
source = []
destination=[]
duration = []
total_stops = []
price=[]

In [87]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=BLR&destinationCountry=IN&flexi=0&flight_depart_date=28%2F03%2F2022&hb=0&noOfSegments=1&origin=BOM&originCountry=IN&type=O&unique=572111730468&version=1.1&viewName=normal')
time.sleep(2)

In [88]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//div/div/div/div[2]/div[1]/div/div[2]/span')
    for i in tag:
        Airline_name.append(i.text)
        
    l1 = len(Airline_name)
    length= l1
except:
    Airline_name.append('Nan')
    
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
except:
    Date.append('Nan')

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')
    
len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25)

In [89]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=BLR&destinationCountry=IN&flexi=0&flight_depart_date=30%2F03%2F2022&hb=0&noOfSegments=1&origin=BOM&originCountry=IN&type=O&unique=572111730468&version=1.1&viewName=normal')
time.sleep(2)

In [90]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[1]/div/div[2]/span')
    for i in tag:
        Airline_name.append(i.text)
        
    l2 = len(Airline_name)-l1
    length=l2
except:
    Airline_name.append('Nan')
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
        
except:
    pass

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')
    
len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50)

In [91]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=BLR&destinationCountry=IN&flexi=0&flight_depart_date=02%2F04%2F2022&hb=0&noOfSegments=1&origin=BOM&originCountry=IN&type=O&unique=572111730468&version=1.1&viewName=normal')
time.sleep(2)

In [92]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[1]/div/div[2]/span')
    for i in tag:
        Airline_name.append(i.text)
        
    l3 = len(Airline_name)-l2-l1
    length=l3
except:
    Airline_name.append('Nan')
    
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
        
except:
    pass

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')
    
len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75)

In [93]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=BLR&destinationCountry=IN&flexi=0&flight_depart_date=07%2F04%2F2022&hb=0&noOfSegments=1&origin=BOM&originCountry=IN&type=O&unique=572111730468&version=1.1&viewName=normal')
time.sleep(2)

In [95]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[1]/div/div[2]/span')
    for i in tag:
        Airline_name.append(i.text)
        
    l4 = len(Airline_name)-l2-l1-l3
    length=l4
except:
    Airline_name.append('Nan')
    
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
        
except:
    pass

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')
    
len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100)

In [96]:
df3 = pd.DataFrame({'Airline Name':Airline_name, 'Departure Date':Date,'Arrival Time':arrival_time,'Departure Time':dep_time, 'Source':source, 'Destination':destination,'Duration':duration,'Total Stops':total_stops,'Price':price})
df3

,Airline Name,Departure Date,Arrival Time,Departure Time,Source,Destination,Duration,Total Stops,Price
0,IndiGo,,00:10\n+ 1 day,22:40,Mumbai,Bangalore,1h 30m,Non Stop,"6,258"
1,IndiGo,,07:40,06:05,Mumbai,Bangalore,1h 35m,Non Stop,"6,258"
2,Go First,,07:45,06:10,Mumbai,Bangalore,1h 35m,Non Stop,"6,258"
3,IndiGo,,13:20,11:45,Mumbai,Bangalore,1h 35m,Non Stop,"6,258"
4,Air Asia,,23:35,22:00,Mumbai,Bangalore,1h 35m,Non Stop,"6,258"
...,...,...,...,...,...,...,...,...,...
95,Vistara,,20:55,19:10,Mumbai,Bangalore,1h 45m,Non Stop,"5,103"
96,Vistara,,07:50,06:00,Mumbai,Bangalore,1h 50m,Non Stop,"5,103"
97,Vistara,,08:50,07:00,Mumbai,Bangalore,1h 50m,Non Stop,"5,103"
98,IndiGo,,23:40,19:55,Mumbai,Bangalore,3h 45m,1 Stop,"5,103"
99,IndiGo,,10:35,06:05,Mumbai,Bangalore,4h 30m,1 Stop,"5,103"

##  Kolkata - Chennai

In [108]:
Airline_name = []
Date = []
arrival_time=[]
dep_time = []
source = []
destination=[]
duration = []
total_stops = []
price=[]

In [109]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=MAA&destinationCountry=IN&flexi=0&flight_depart_date=26%2F03%2F2022&hb=0&noOfSegments=1&origin=CCU&originCountry=IN&type=O&unique=195367049249&version=1.1&viewName=normal')
time.sleep(2)

In [110]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//div/div/div/div[2]/div[1]/div/div[2]/span')
    for i in tag:
        Airline_name.append(i.text)
        
    l1 = len(Airline_name)
    length= l1
except:
    Airline_name.append('Nan')
    
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
except:
    Date.append('Nan')

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')
    
len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25)

In [111]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=MAA&destinationCountry=IN&flexi=0&flight_depart_date=09%2F04%2F2022&hb=0&noOfSegments=1&origin=CCU&originCountry=IN&type=O&unique=195367049249&version=1.1&viewName=normal')
time.sleep(2)

In [112]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//div/div/div/div[2]/div[1]/div/div[2]/span')
    for i in tag:
        Airline_name.append(i.text)
        
    l2 = len(Airline_name)
    length= len(Airline_name)-l1
except:
    Airline_name.append('Nan')
    
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
except:
    Date.append('Nan')

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')
    
len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50)

In [113]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=MAA&destinationCountry=IN&flexi=0&flight_depart_date=14%2F04%2F2022&hb=0&noOfSegments=1&origin=CCU&originCountry=IN&type=O&unique=195367049249&version=1.1&viewName=normal')
time.sleep(2)

In [114]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[1]/div/div[2]/span')
    for i in tag:
        Airline_name.append(i.text)
        
    l3 = len(Airline_name)-l2-l1
    length=l3
except:
    Airline_name.append('Nan')
    
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
        
except:
    pass

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')
    
len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(75, 75, 50, 75, 75, 75, 75, 75, 75, 75, 75)

In [115]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=MAA&destinationCountry=IN&flexi=0&flight_depart_date=19%2F04%2F2022&hb=0&noOfSegments=1&origin=CCU&originCountry=IN&type=O&unique=195367049249&version=1.1&viewName=normal')
time.sleep(2)

In [119]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[1]/div/div[2]/span')
    for i in tag:
        Airline_name.append(i.text)
        
    l4 = len(Airline_name)-l2-l1-l3
    length=l4
except:
    Airline_name.append('Nan')
    
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
        
except:
    pass 

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')

len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100)

In [120]:
df4 = pd.DataFrame({'Airline Name':Airline_name, 'Departure Date':Date,'Arrival Time':arrival_time,'Departure Time':dep_time, 'Source':source, 'Destination':destination,'Duration':duration,'Total Stops':total_stops,'Price':price})
df4

,Airline Name,Departure Date,Arrival Time,Departure Time,Source,Destination,Duration,Total Stops,Price
0,SpiceJet,"Wed, 23 Mar",23:55,21:40,Kolkata,Chennai,2h 15m,Non Stop,"7,854"
1,IndiGo,"Wed, 23 Mar",19:00,12:55,Kolkata,Chennai,6h 05m,1 Stop,"7,854"
2,IndiGo,"Wed, 23 Mar",21:05,14:50,Kolkata,Chennai,6h 15m,1 Stop,"7,854"
3,IndiGo,"Wed, 23 Mar",21:05,11:25,Kolkata,Chennai,9h 40m,1 Stop,"7,854"
4,SpiceJet,"Wed, 23 Mar",07:00\n+ 1 day,20:30,Kolkata,Chennai,10h 30m,1 Stop,"7,854"
...,...,...,...,...,...,...,...,...,...
95,IndiGo,,08:00\n+ 1 day,23:10,Kolkata,Chennai,8h 50m,1 Stop,"6,384"
96,IndiGo,,15:55,06:45,Kolkata,Chennai,9h 10m,1 Stop,"6,384"
97,IndiGo,,16:25,07:15,Kolkata,Chennai,9h 10m,1 Stop,"6,384"
98,IndiGo,,15:10,05:55,Kolkata,Chennai,9h 15m,1 Stop,"6,384"
99,IndiGo,,23:35,13:20,Kolkata,Chennai,10h 15m,1 Stop,"6,384"

## Kochi - Pune

In [125]:
Airline_name = []
Date = []
arrival_time=[]
dep_time = []
source = []
destination=[]
duration = []
total_stops = []
price=[]

In [123]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=PNQ&destinationCountry=IN&flexi=0&flight_depart_date=26%2F03%2F2022&hb=0&noOfSegments=1&origin=COK&originCountry=IN&type=O&unique=1224358165074&version=1.1&viewName=normal')
time.sleep(2)

In [126]:
for i in range(1000):
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")

In [127]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//div/div/div/div[2]/div[1]/div/div[2]/span')
    for i in tag:
        Airline_name.append(i.text)
        
    l1 = len(Airline_name)
    length= l1
except:
    Airline_name.append('Nan')
    
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
except:
    Date.append('Nan')

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')
    
len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22)

In [129]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=MAA&destinationCountry=IN&flexi=0&flight_depart_date=17%2F04%2F2022&hb=0&noOfSegments=1&origin=CCU&originCountry=IN&type=O&unique=195367049249&version=1.1&viewName=normal')
time.sleep(2)

In [130]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//div/div/div/div[2]/div[1]/div/div[2]/span')
    for i in tag:
        Airline_name.append(i.text)
        
    l2 = len(Airline_name)-l1
    length= l2
except:
    Airline_name.append('Nan')
    
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
except:
    Date.append('Nan')

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')
    
len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47)

In [131]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=MAA&destinationCountry=IN&flexi=0&flight_depart_date=21%2F04%2F2022&hb=0&noOfSegments=1&origin=CCU&originCountry=IN&type=O&unique=195367049249&version=1.1&viewName=normal')
time.sleep(2)

In [132]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[1]/div/div[2]/span')
    for i in tag:
        Airline_name.append(i.text)
        
    l3 = len(Airline_name)-l2-l1
    length=l3
except:
    Airline_name.append('Nan')
    
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
        
except:
    pass

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')
    
len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72)

In [141]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=MAA&destinationCountry=IN&flexi=0&flight_depart_date=23%2F04%2F2022&hb=0&noOfSegments=1&origin=CCU&originCountry=IN&type=O&unique=195367049249&version=1.1&viewName=normal')
time.sleep(2)

In [134]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[1]/div/div[2]/span')
    for i in tag:
        Airline_name.append(i.text)
        
    l4 = len(Airline_name)-l2-l1-l3
    length=l4
except:
    Airline_name.append('Nan')
    
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
        
except:
    pass 

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')

len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97)

In [136]:
df5 = pd.DataFrame({'Airline Name':Airline_name, 'Departure Date':Date,'Arrival Time':arrival_time,'Departure Time':dep_time, 'Source':source, 'Destination':destination,'Duration':duration,'Total Stops':total_stops,'Price':price})
df5

,Airline Name,Departure Date,Arrival Time,Departure Time,Source,Destination,Duration,Total Stops,Price
0,IndiGo,"Wed, 23 Mar",03:35\n+ 1 day,19:00,Kochi,Pune,8h 35m,1 Stop,"7,197"
1,IndiGo,"Wed, 23 Mar",05:05\n+ 1 day,19:00,Kochi,Pune,10h 05m,1 Stop,"7,197"
2,IndiGo,"Wed, 23 Mar",02:10,00:25,Kochi,Pune,1h 45m,Non Stop,"9,139"
3,IndiGo,"Wed, 23 Mar",00:05\n+ 1 day,15:05,Kochi,Pune,9h 00m,1 Stop,"9,549"
4,IndiGo,"Wed, 23 Mar",00:05\n+ 1 day,13:45,Kochi,Pune,10h 20m,1 Stop,"9,549"
...,...,...,...,...,...,...,...,...,...
92,IndiGo,,12:10,05:40,Kolkata,Chennai,6h 30m,1 Stop,"7,907"
93,IndiGo,,12:10,04:30,Kolkata,Chennai,7h 40m,1 Stop,"7,907"
94,IndiGo,,09:05,04:30,Kolkata,Chennai,4h 35m,1 Stop,"8,117"
95,IndiGo,,10:50,05:40,Kolkata,Chennai,5h 10m,1 Stop,"8,117"
96,IndiGo,,10:50,04:30,Kolkata,Chennai,6h 20m,1 Stop,"8,117"

## Hydrabad-Ahemdabad

In [160]:
Airline_name = []
Date = []
arrival_time=[]
dep_time = []
source = []
destination=[]
duration = []
total_stops = []
price=[]

In [161]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=AMD&destinationCountry=IN&flexi=0&flight_depart_date=23%2F04%2F2022&hb=0&noOfSegments=1&origin=HYD&originCountry=IN&type=O&unique=819888518030&version=1.1&viewName=normal')
time.sleep(2)

In [162]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//div/span[@class="i-b text ellipsis"]')
    for i in tag:
        Airline_name.append(i.text)
        
    l1 = len(Airline_name)
    length= l1
except:
    Airline_name.append('Nan')
    
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
except:
    Date.append('Nan')

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')
    
len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25)

In [163]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=AMD&destinationCountry=IN&flexi=0&flight_depart_date=12%2F04%2F2022&hb=0&noOfSegments=1&origin=HYD&originCountry=IN&type=O&unique=819888518030&version=1.1&viewName=normal')
time.sleep(2)

In [164]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//div/div/div/div[2]/div[1]/div/div[2]/span')
    for i in tag:
        Airline_name.append(i.text)
        
    l2 = len(Airline_name)-l1
    length= l2
except:
    Airline_name.append('Nan')
    
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
except:
    Date.append('Nan')

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')
    
len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50)

In [166]:

#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=AMD&destinationCountry=IN&flexi=0&flight_depart_date=07%2F04%2F2022&hb=0&noOfSegments=1&origin=HYD&originCountry=IN&type=O&unique=819888518030&version=1.1&viewName=normal')
time.sleep(2)

In [167]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[1]/div/div[2]/span')
    for i in tag:
        Airline_name.append(i.text)
        
    l3 = len(Airline_name)-l2-l1
    length=l3
except:
    Airline_name.append('Nan')
    
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
        
except:
    pass

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')
    
len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75)

In [168]:

#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=AMD&destinationCountry=IN&flexi=0&flight_depart_date=19%2F04%2F2022&hb=0&noOfSegments=1&origin=HYD&originCountry=IN&type=O&unique=819888518030&version=1.1&viewName=normal')
time.sleep(2)

In [169]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//span[@class="i-b text ellipsis"]')
    for i in tag:
        Airline_name.append(i.text)
        
    l4 = len(Airline_name)-l2-l1-l3
    length=l4
except:
    Airline_name.append('Nan')
    
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
        
except:
    pass 

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')

len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100)

In [170]:
df6 = pd.DataFrame({'Airline Name':Airline_name, 'Departure Date':Date,'Arrival Time':arrival_time,'Departure Time':dep_time, 'Source':source, 'Destination':destination,'Duration':duration,'Total Stops':total_stops,'Price':price})
df6

,Airline Name,Departure Date,Arrival Time,Departure Time,Source,Destination,Duration,Total Stops,Price
0,Go First,,07:30,05:40,Hyderabad,Ahmedabad,1h 50m,Non Stop,"4,452"
1,IndiGo,,08:15,06:25,Hyderabad,Ahmedabad,1h 50m,Non Stop,"4,663"
2,IndiGo,,23:45,22:05,Hyderabad,Ahmedabad,1h 40m,Non Stop,"4,768"
3,IndiGo,,22:15,20:40,Hyderabad,Ahmedabad,1h 35m,Non Stop,"5,503"
4,Air India,,20:00\n+ 1 day,22:15,Hyderabad,Ahmedabad,21h 45m,1 Stop,"6,868"
...,...,...,...,...,...,...,...,...,...
95,IndiGo,,01:50\n+ 1 day,20:05,Hyderabad,Ahmedabad,5h 45m,1 Stop,"6,207"
96,IndiGo,,03:50\n+ 1 day,20:30,Hyderabad,Ahmedabad,7h 20m,1 Stop,"6,207"
97,IndiGo,,06:20\n+ 1 day,23:15,Hyderabad,Ahmedabad,7h 05m,1 Stop,"6,663"
98,IndiGo,,06:05\n+ 1 day,22:15,Hyderabad,Ahmedabad,7h 50m,1 Stop,"6,663"
99,IndiGo,,01:45\n+ 1 day,17:50,Hyderabad,Ahmedabad,7h 55m,1 Stop,"6,663"

## Chennai - Mumbai

In [171]:
Airline_name = []
Date = []
arrival_time=[]
dep_time = []
source = []
destination=[]
duration = []
total_stops = []
price=[]

In [172]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=BOM&destinationCountry=IN&flexi=0&flight_depart_date=30%2F03%2F2022&hb=0&noOfSegments=1&origin=MAA&originCountry=IN&type=O&unique=788143755506&version=1.1&viewName=normal')
time.sleep(2)

In [173]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//div/span[@class="i-b text ellipsis"]')
    for i in tag:
        Airline_name.append(i.text)
        
    l1 = len(Airline_name)
    length= l1
except:
    Airline_name.append('Nan')
    
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
except:
    Date.append('Nan')

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')
    
len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25)

In [174]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=BOM&destinationCountry=IN&flexi=0&flight_depart_date=02%2F04%2F2022&hb=0&noOfSegments=1&origin=MAA&originCountry=IN&type=O&unique=788143755506&version=1.1&viewName=normal')
time.sleep(2)

In [175]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//div/div/div/div[2]/div[1]/div/div[2]/span')
    for i in tag:
        Airline_name.append(i.text)
        
    l2 = len(Airline_name)-l1
    length= l2
except:
    Airline_name.append('Nan')
    
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
except:
    Date.append('Nan')

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')
    
len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50)

In [176]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=BOM&destinationCountry=IN&flexi=0&flight_depart_date=23%2F03%2F2022&hb=0&noOfSegments=1&origin=MAA&originCountry=IN&type=O&unique=788143755506&version=1.1&viewName=normal')
time.sleep(2)

In [177]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[1]/div/div[2]/span')
    for i in tag:
        Airline_name.append(i.text)
        
    l3 = len(Airline_name)-l2-l1
    length=l3
except:
    Airline_name.append('Nan')
    
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
        
except:
    pass

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')
    
len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75)

In [178]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=BOM&destinationCountry=IN&flexi=0&flight_depart_date=26%2F03%2F2022&hb=0&noOfSegments=1&origin=MAA&originCountry=IN&type=O&unique=788143755506&version=1.1&viewName=normal')
time.sleep(2)

In [179]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//span[@class="i-b text ellipsis"]')
    for i in tag:
        Airline_name.append(i.text)
        
    l4 = len(Airline_name)-l2-l1-l3
    length=l4
except:
    Airline_name.append('Nan')
    
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
        
except:
    pass 

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')

len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100)

In [180]:
df7 = pd.DataFrame({'Airline Name':Airline_name, 'Departure Date':Date,'Arrival Time':arrival_time,'Departure Time':dep_time, 'Source':source, 'Destination':destination,'Duration':duration,'Total Stops':total_stops,'Price':price})
df7

,Airline Name,Departure Date,Arrival Time,Departure Time,Source,Destination,Duration,Total Stops,Price
0,IndiGo,,09:55,08:10,Chennai,Mumbai,1h 45m,Non Stop,"7,247"
1,IndiGo,,05:55,04:05,Chennai,Mumbai,1h 50m,Non Stop,"7,247"
2,Go First,,06:50,05:00,Chennai,Mumbai,1h 50m,Non Stop,"7,247"
3,IndiGo,,13:40,11:50,Chennai,Mumbai,1h 50m,Non Stop,"7,247"
4,IndiGo,,14:45,12:55,Chennai,Mumbai,1h 50m,Non Stop,"7,247"
...,...,...,...,...,...,...,...,...,...
95,IndiGo,"Wed, 23 Mar",23:25,17:05,Chennai,Mumbai,6h 20m,1 Stop,"9,347"
96,IndiGo,"Wed, 23 Mar",23:15,16:30,Chennai,Mumbai,6h 45m,1 Stop,"9,347"
97,IndiGo,"Wed, 23 Mar",21:35,14:30,Chennai,Mumbai,7h 05m,1 Stop,"9,347"
98,IndiGo,"Wed, 23 Mar",00:35\n+ 1 day,16:30,Chennai,Mumbai,8h 05m,1 Stop,"9,347"
99,IndiGo,"Wed, 23 Mar",21:35,13:05,Chennai,Mumbai,8h 30m,1 Stop,"9,347"

## Kochi - Pune

In [182]:
Airline_name = []
Date = []
arrival_time=[]
dep_time = []
source = []
destination=[]
duration = []
total_stops = []
price=[]

In [183]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=PNQ&destinationCountry=IN&flexi=0&flight_depart_date=28%2F03%2F2022&hb=0&noOfSegments=1&origin=COK&originCountry=IN&type=O&unique=1486404196611&version=1.1&viewName=normal')
time.sleep(2)

In [184]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//div/span[@class="i-b text ellipsis"]')
    for i in tag:
        Airline_name.append(i.text)
        
    l1 = len(Airline_name)
    length= l1
except:
    Airline_name.append('Nan')
    
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
except:
    Date.append('Nan')

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')
    
len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25)

In [185]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=PNQ&destinationCountry=IN&flexi=0&flight_depart_date=05%2F04%2F2022&hb=0&noOfSegments=1&origin=COK&originCountry=IN&type=O&unique=1486404196611&version=1.1&viewName=normal')
time.sleep(2)

In [186]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//div/div/div/div[2]/div[1]/div/div[2]/span')
    for i in tag:
        Airline_name.append(i.text)
        
    l2 = len(Airline_name)-l1
    length= l2
except:
    Airline_name.append('Nan')
    
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
except:
    Date.append('Nan')

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')
    
len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50)

In [187]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=PNQ&destinationCountry=IN&flexi=0&flight_depart_date=11%2F04%2F2022&hb=0&noOfSegments=1&origin=COK&originCountry=IN&type=O&unique=1486404196611&version=1.1&viewName=normal')
time.sleep(2)

In [188]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[1]/div/div[2]/span')
    for i in tag:
        Airline_name.append(i.text)
        
    l3 = len(Airline_name)-l2-l1
    length=l3
except:
    Airline_name.append('Nan')
    
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
        
except:
    pass

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')
    
len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75)

In [189]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=PNQ&destinationCountry=IN&flexi=0&flight_depart_date=17%2F04%2F2022&hb=0&noOfSegments=1&origin=COK&originCountry=IN&type=O&unique=1486404196611&version=1.1&viewName=normal')
time.sleep(2)

In [190]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//span[@class="i-b text ellipsis"]')
    for i in tag:
        Airline_name.append(i.text)
        
    l4 = len(Airline_name)-l2-l1-l3
    length=l4
except:
    Airline_name.append('Nan')
    
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
        
except:
    pass 

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')

len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100)

In [191]:
df8 = pd.DataFrame({'Airline Name':Airline_name, 'Departure Date':Date,'Arrival Time':arrival_time,'Departure Time':dep_time, 'Source':source, 'Destination':destination,'Duration':duration,'Total Stops':total_stops,'Price':price})
df8

,Airline Name,Departure Date,Arrival Time,Departure Time,Source,Destination,Duration,Total Stops,Price
0,IndiGo,,15:05,11:30,Kochi,Pune,3h 35m,1 Stop,"7,197"
1,IndiGo,,17:15,12:30,Kochi,Pune,4h 45m,1 Stop,"7,197"
2,IndiGo,,15:05,09:40,Kochi,Pune,5h 25m,1 Stop,"7,197"
3,IndiGo,,00:20\n+ 1 day,18:55,Kochi,Pune,5h 25m,1 Stop,"7,197"
4,IndiGo,,23:30,17:35,Kochi,Pune,5h 55m,1 Stop,"7,197"
...,...,...,...,...,...,...,...,...,...
95,Vistara,,12:35\n+ 1 day,09:15,Kochi,Pune,27h 20m,1 Stop,"14,818"
96,Air India,,11:35\n+ 1 day,08:05,Kochi,Pune,27h 30m,3 Stop(s),"15,019"
97,IndiGo,,00:20\n+ 1 day,15:00,Kochi,Pune,9h 20m,1 Stop,"15,282"
98,IndiGo,,06:50\n+ 1 day,21:15,Kochi,Pune,9h 35m,1 Stop,"15,387"
99,IndiGo,,01:35\n+ 1 day,23:50,Kochi,Pune,1h 45m,Non Stop,"15,649"

## New Delhi-Banglore

In [192]:
Airline_name = []
Date = []
arrival_time=[]
dep_time = []
source = []
destination=[]
duration = []
total_stops = []
price=[]

In [193]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=BLR&destinationCountry=IN&flexi=0&flight_depart_date=01%2F04%2F2022&hb=0&noOfSegments=1&origin=DEL&originCountry=IN&type=O&unique=323410524515&version=1.1&viewName=normal')
time.sleep(2)

In [194]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//div/span[@class="i-b text ellipsis"]')
    for i in tag:
        Airline_name.append(i.text)
        
    l1 = len(Airline_name)
    length= l1
except:
    Airline_name.append('Nan')
    
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
except:
    Date.append('Nan')

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')
    
len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25)

In [195]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=BLR&destinationCountry=IN&flexi=0&flight_depart_date=04%2F04%2F2022&hb=0&noOfSegments=1&origin=DEL&originCountry=IN&type=O&unique=323410524515&version=1.1&viewName=normal')
time.sleep(2)

In [196]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//div/div/div/div[2]/div[1]/div/div[2]/span')
    for i in tag:
        Airline_name.append(i.text)
        
    l2 = len(Airline_name)-l1
    length= l2
except:
    Airline_name.append('Nan')
    
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
except:
    Date.append('Nan')

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')
    
len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50)

In [197]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=BLR&destinationCountry=IN&flexi=0&flight_depart_date=13%2F04%2F2022&hb=0&noOfSegments=1&origin=DEL&originCountry=IN&type=O&unique=323410524515&version=1.1&viewName=normal')
time.sleep(2)

In [198]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[1]/div/div[2]/span')
    for i in tag:
        Airline_name.append(i.text)
        
    l3 = len(Airline_name)-l2-l1
    length=l3
except:
    Airline_name.append('Nan')
    
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
        
except:
    pass

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')
    
len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75)

In [199]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=BLR&destinationCountry=IN&flexi=0&flight_depart_date=21%2F04%2F2022&hb=0&noOfSegments=1&origin=DEL&originCountry=IN&type=O&unique=323410524515&version=1.1&viewName=normal')
time.sleep(2)

In [200]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//span[@class="i-b text ellipsis"]')
    for i in tag:
        Airline_name.append(i.text)
        
    l4 = len(Airline_name)-l2-l1-l3
    length=l4
except:
    Airline_name.append('Nan')
    
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
        
except:
    pass 

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')

len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100)

In [201]:
df9 = pd.DataFrame({'Airline Name':Airline_name, 'Departure Date':Date,'Arrival Time':arrival_time,'Departure Time':dep_time, 'Source':source, 'Destination':destination,'Duration':duration,'Total Stops':total_stops,'Price':price})
df9

,Airline Name,Departure Date,Arrival Time,Departure Time,Source,Destination,Duration,Total Stops,Price
0,Air Asia,,10:40,08:10,New Delhi,Bangalore,2h 30m,Non Stop,"8,160"
1,IndiGo,,19:55,17:25,New Delhi,Bangalore,2h 30m,Non Stop,"8,160"
2,Go First,,08:35,06:00,New Delhi,Bangalore,2h 35m,Non Stop,"8,160"
3,IndiGo,,15:35,13:00,New Delhi,Bangalore,2h 35m,Non Stop,"8,160"
4,IndiGo,,11:00,08:20,New Delhi,Bangalore,2h 40m,Non Stop,"8,160"
...,...,...,...,...,...,...,...,...,...
95,Vistara,,22:40,19:50,New Delhi,Bangalore,2h 50m,Non Stop,"5,325"
96,IndiGo,,23:00,20:10,New Delhi,Bangalore,2h 50m,Non Stop,"5,325"
97,Air India,,00:05\n+ 1 day,21:15,New Delhi,Bangalore,2h 50m,Non Stop,"5,325"
98,IndiGo,,01:45\n+ 1 day,22:55,New Delhi,Bangalore,2h 50m,Non Stop,"5,325"
99,IndiGo,,09:50,06:55,New Delhi,Bangalore,2h 55m,Non Stop,"5,325"

## Chennai-Mumbai

In [202]:
Airline_name = []
Date = []
arrival_time=[]
dep_time = []
source = []
destination=[]
duration = []
total_stops = []
price=[]

In [203]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=BOM&destinationCountry=IN&flexi=0&flight_depart_date=31%2F03%2F2022&hb=0&noOfSegments=1&origin=MAA&originCountry=IN&type=O&unique=464721648785&version=1.1&viewName=normal')
time.sleep(2)

In [204]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//div/span[@class="i-b text ellipsis"]')
    for i in tag:
        Airline_name.append(i.text)
        
    l1 = len(Airline_name)
    length= l1
except:
    Airline_name.append('Nan')
    
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
except:
    Date.append('Nan')

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')
    
len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25)

In [205]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=BOM&destinationCountry=IN&flexi=0&flight_depart_date=03%2F04%2F2022&hb=0&noOfSegments=1&origin=MAA&originCountry=IN&type=O&unique=464721648785&version=1.1&viewName=normal')
time.sleep(2)

In [206]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//div/div/div/div[2]/div[1]/div/div[2]/span')
    for i in tag:
        Airline_name.append(i.text)
        
    l2 = len(Airline_name)-l1
    length= l2
except:
    Airline_name.append('Nan')
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
except:
    Date.append('Nan')

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')
    
len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50)

In [207]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=BOM&destinationCountry=IN&flexi=0&flight_depart_date=10%2F04%2F2022&hb=0&noOfSegments=1&origin=MAA&originCountry=IN&type=O&unique=464721648785&version=1.1&viewName=normal')
time.sleep(2)

In [208]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[1]/div/div[2]/span')
    for i in tag:
        Airline_name.append(i.text)
        
    l3 = len(Airline_name)-l2-l1
    length=l3
except:
    Airline_name.append('Nan')
    
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
        
except:
    pass

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')
    
len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75)

In [209]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=BOM&destinationCountry=IN&flexi=0&flight_depart_date=16%2F04%2F2022&hb=0&noOfSegments=1&origin=MAA&originCountry=IN&type=O&unique=464721648785&version=1.1&viewName=normal')
time.sleep(2)

In [210]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//span[@class="i-b text ellipsis"]')
    for i in tag:
        Airline_name.append(i.text)
        
    l4 = len(Airline_name)-l2-l1-l3
    length=l4
except:
    Airline_name.append('Nan')
    
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
        
except:
    pass 

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')

len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100)

In [211]:
df10 = pd.DataFrame({'Airline Name':Airline_name, 'Departure Date':Date,'Arrival Time':arrival_time,'Departure Time':dep_time, 'Source':source, 'Destination':destination,'Duration':duration,'Total Stops':total_stops,'Price':price})
df10

,Airline Name,Departure Date,Arrival Time,Departure Time,Source,Destination,Duration,Total Stops,Price
0,IndiGo,,05:55,04:05,Chennai,Mumbai,1h 50m,Non Stop,"7,247"
1,Go First,,06:50,05:00,Chennai,Mumbai,1h 50m,Non Stop,"7,247"
2,IndiGo,,13:40,11:50,Chennai,Mumbai,1h 50m,Non Stop,"7,247"
3,IndiGo,,14:45,12:55,Chennai,Mumbai,1h 50m,Non Stop,"7,247"
4,SpiceJet,,08:20,06:25,Chennai,Mumbai,1h 55m,Non Stop,"7,247"
...,...,...,...,...,...,...,...,...,...
95,IndiGo,,19:55,18:00,Chennai,Mumbai,1h 55m,Non Stop,"5,987"
96,IndiGo,,00:40\n+ 1 day,20:05,Chennai,Mumbai,4h 35m,1 Stop,"6,092"
97,SpiceJet,,20:10,07:50,Chennai,Mumbai,12h 20m,1 Stop,"7,320"
98,SpiceJet,,08:10\n+ 1 day,07:50,Chennai,Mumbai,24h 20m,1 Stop,"7,320"
99,IndiGo,,20:35,17:00,Chennai,Mumbai,3h 35m,1 Stop,"7,615"

## Ahmedabad -Bangalore

In [212]:
Airline_name = []
Date = []
arrival_time=[]
dep_time = []
source = []
destination=[]
duration = []
total_stops = []
price=[]

In [216]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=BLR&destinationCountry=IN&flexi=0&flight_depart_date=29%2F03%2F2022&hb=0&noOfSegments=1&origin=AMD&originCountry=IN&type=O&unique=1106657968818&version=1.1&viewName=normal')
time.sleep(2)

In [217]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//div/span[@class="i-b text ellipsis"]')
    for i in tag:
        Airline_name.append(i.text)
        
    l1 = len(Airline_name)
    length= l1
except:
    Airline_name.append('Nan')
    
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
except:
    Date.append('Nan')

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')
    
len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25)

In [218]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=BLR&destinationCountry=IN&flexi=0&flight_depart_date=07%2F04%2F2022&hb=0&noOfSegments=1&origin=AMD&originCountry=IN&type=O&unique=1106657968818&version=1.1&viewName=normal')
time.sleep(2)

In [219]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//div/div/div/div[2]/div[1]/div/div[2]/span')
    for i in tag:
        Airline_name.append(i.text)
        
    l2 = len(Airline_name)-l1
    length= l2
except:
    Airline_name.append('Nan')
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
except:
    Date.append('Nan')

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')
    
len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50)

In [220]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=BLR&destinationCountry=IN&flexi=0&flight_depart_date=12%2F04%2F2022&hb=0&noOfSegments=1&origin=AMD&originCountry=IN&type=O&unique=1106657968818&version=1.1&viewName=normal')
time.sleep(2)

In [222]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[1]/div/div[2]/span')
    for i in tag:
        Airline_name.append(i.text)
        
    l3 = len(Airline_name)-l2-l1
    length=l3
except:
    Airline_name.append('Nan')
    
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
        
except:
    pass

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')
    
len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75)

In [223]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=BLR&destinationCountry=IN&flexi=0&flight_depart_date=22%2F04%2F2022&hb=0&noOfSegments=1&origin=AMD&originCountry=IN&type=O&unique=1106657968818&version=1.1&viewName=normal')
time.sleep(2)

In [224]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//span[@class="i-b text ellipsis"]')
    for i in tag:
        Airline_name.append(i.text)
        
    l4 = len(Airline_name)-l2-l1-l3
    length=l4
except:
    Airline_name.append('Nan')
    
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
        
except:
    pass 

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')

len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100)

In [225]:
df11 = pd.DataFrame({'Airline Name':Airline_name, 'Departure Date':Date,'Arrival Time':arrival_time,'Departure Time':dep_time, 'Source':source, 'Destination':destination,'Duration':duration,'Total Stops':total_stops,'Price':price})
df11

,Airline Name,Departure Date,Arrival Time,Departure Time,Source,Destination,Duration,Total Stops,Price
0,IndiGo,,09:45,07:40,Ahmedabad,Bangalore,2h 05m,Non Stop,"7,266"
1,Go First,,10:10,08:05,Ahmedabad,Bangalore,2h 05m,Non Stop,"7,266"
2,IndiGo,,23:25,21:20,Ahmedabad,Bangalore,2h 05m,Non Stop,"7,266"
3,IndiGo,,01:40\n+ 1 day,23:35,Ahmedabad,Bangalore,2h 05m,Non Stop,"7,266"
4,IndiGo,,06:50,04:30,Ahmedabad,Bangalore,2h 20m,Non Stop,"7,266"
...,...,...,...,...,...,...,...,...,...
95,Go First,,02:55\n+ 1 day,21:15,Ahmedabad,Bangalore,5h 40m,1 Stop,"7,791"
96,IndiGo,,11:35,06:40,Ahmedabad,Bangalore,4h 55m,1 Stop,"7,844"
97,IndiGo,,07:40\n+ 1 day,23:25,Ahmedabad,Bangalore,8h 15m,1 Stop,"7,844"
98,IndiGo,,06:05\n+ 1 day,20:50,Ahmedabad,Bangalore,9h 15m,1 Stop,"7,844"
99,IndiGo,,09:30,04:30,Ahmedabad,Bangalore,5h 00m,1 Stop,"7,949"

## Delhi-Kolkata

In [226]:
Airline_name = []
Date = []
arrival_time=[]
dep_time = []
source = []
destination=[]
duration = []
total_stops = []
price=[]

In [227]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=CCU&destinationCountry=IN&flexi=0&flight_depart_date=26%2F04%2F2022&hb=0&noOfSegments=1&origin=DEL&originCountry=IN&type=O&unique=294701425513&version=1.1&viewName=normal')
time.sleep(2)

In [229]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//div/span[@class="i-b text ellipsis"]')
    for i in tag:
        Airline_name.append(i.text)
        
    l1 = len(Airline_name)
    length= l1
except:
    Airline_name.append('Nan')
    
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
except:
    Date.append('Nan')

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')
    
len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25)

In [230]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=CCU&destinationCountry=IN&flexi=0&flight_depart_date=15%2F04%2F2022&hb=0&noOfSegments=1&origin=DEL&originCountry=IN&type=O&unique=294701425513&version=1.1&viewName=normal')
time.sleep(2)

In [231]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//div/div/div/div[2]/div[1]/div/div[2]/span')
    for i in tag:
        Airline_name.append(i.text)
        
    l2 = len(Airline_name)-l1
    length= l2
except:
    Airline_name.append('Nan')
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
except:
    Date.append('Nan')

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')
    
len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50)

In [232]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=CCU&destinationCountry=IN&flexi=0&flight_depart_date=08%2F04%2F2022&hb=0&noOfSegments=1&origin=DEL&originCountry=IN&type=O&unique=294701425513&version=1.1&viewName=normal')
time.sleep(2)

In [233]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[1]/div/div[2]/span')
    for i in tag:
        Airline_name.append(i.text)
        
    l3 = len(Airline_name)-l2-l1
    length=l3
except:
    Airline_name.append('Nan')
    
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
        
except:
    pass

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')
    
len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75)

In [237]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=CCU&destinationCountry=IN&flexi=0&flight_depart_date=03%2F04%2F2022&hb=0&noOfSegments=1&origin=DEL&originCountry=IN&type=O&unique=294701425513&version=1.1&viewName=normal')
time.sleep(2)

In [238]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//span[@class="i-b text ellipsis"]')
    for i in tag:
        Airline_name.append(i.text)
        
    l4 = len(Airline_name)-l2-l1-l3
    length=l4
except:
    Airline_name.append('Nan')
    
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
        
except:
    pass 

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')

len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100)

In [239]:
df12 = pd.DataFrame({'Airline Name':Airline_name, 'Departure Date':Date,'Arrival Time':arrival_time,'Departure Time':dep_time, 'Source':source, 'Destination':destination,'Duration':duration,'Total Stops':total_stops,'Price':price})
df12

,Airline Name,Departure Date,Arrival Time,Departure Time,Source,Destination,Duration,Total Stops,Price
0,IndiGo,,07:50,06:05,New Delhi,Kolkata,1h 45m,Non Stop,"4,800"
1,SpiceJet,,09:05,07:05,New Delhi,Kolkata,2h 00m,Non Stop,"4,800"
2,IndiGo,,05:05,03:00,New Delhi,Kolkata,2h 05m,Non Stop,"4,800"
3,Go First,,07:50,05:45,New Delhi,Kolkata,2h 05m,Non Stop,"4,800"
4,IndiGo,,10:45,08:40,New Delhi,Kolkata,2h 05m,Non Stop,"4,800"
...,...,...,...,...,...,...,...,...,...
95,Air Asia,,23:00,20:40,New Delhi,Kolkata,2h 20m,Non Stop,"7,320"
96,SpiceJet,,21:55,19:30,New Delhi,Kolkata,2h 25m,Non Stop,"7,320"
97,IndiGo,,18:50,14:00,New Delhi,Kolkata,4h 50m,1 Stop,"7,320"
98,IndiGo,,20:55,15:55,New Delhi,Kolkata,5h 00m,1 Stop,"7,320"
99,IndiGo,,10:30,05:15,New Delhi,Kolkata,5h 15m,1 Stop,"7,320"

## Bangalore -  New Delhi

In [241]:
Airline_name = []
Date = []
arrival_time=[]
dep_time = []
source = []
destination=[]
duration = []
total_stops = []
price=[]

In [242]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=DEL&destinationCountry=IN&flexi=0&flight_depart_date=23%2F03%2F2022&hb=0&noOfSegments=1&origin=BLR&originCountry=IN&type=O&unique=71830440647&version=1.5&viewName=normal')
time.sleep(2)

In [243]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//div/span[@class="i-b text ellipsis"]')
    for i in tag:
        Airline_name.append(i.text)
        
    l1 = len(Airline_name)
    length= l1
except:
    Airline_name.append('Nan')
    
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
except:
    Date.append('Nan')

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')
    
len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25)

In [244]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=DEL&destinationCountry=IN&flexi=0&flight_depart_date=27%2F03%2F2022&hb=0&noOfSegments=1&origin=BLR&originCountry=IN&type=O&unique=71830440647&version=1.5&viewName=normal')
time.sleep(2)

In [245]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//div/div/div/div[2]/div[1]/div/div[2]/span')
    for i in tag:
        Airline_name.append(i.text)
        
    l2 = len(Airline_name)-l1
    length= l2
except:
    Airline_name.append('Nan')
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
except:
    Date.append('Nan')

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')
    
len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50)

In [246]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=DEL&destinationCountry=IN&flexi=0&flight_depart_date=29%2F03%2F2022&hb=0&noOfSegments=1&origin=BLR&originCountry=IN&type=O&unique=71830440647&version=1.5&viewName=normal')
time.sleep(2)

In [247]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[1]/div/div[2]/span')
    for i in tag:
        Airline_name.append(i.text)
        
    l3 = len(Airline_name)-l2-l1
    length=l3
except:
    Airline_name.append('Nan')
    
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
        
except:
    pass

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')
    
len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75)

In [248]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=DEL&destinationCountry=IN&flexi=0&flight_depart_date=09%2F04%2F2022&hb=0&noOfSegments=1&origin=BLR&originCountry=IN&type=O&unique=71830440647&version=1.5&viewName=normal')
time.sleep(2)

In [249]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//span[@class="i-b text ellipsis"]')
    for i in tag:
        Airline_name.append(i.text)
        
    l4 = len(Airline_name)-l2-l1-l3
    length=l4
except:
    Airline_name.append('Nan')
    
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
        
except:
    pass 

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')

len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100)

In [250]:
df13 = pd.DataFrame({'Airline Name':Airline_name, 'Departure Date':Date,'Arrival Time':arrival_time,'Departure Time':dep_time, 'Source':source, 'Destination':destination,'Duration':duration,'Total Stops':total_stops,'Price':price})
df13

,Airline Name,Departure Date,Arrival Time,Departure Time,Source,Destination,Duration,Total Stops,Price
0,SpiceJet,"Thu, 24 Mar",00:45\n+ 1 day,22:05,Bangalore,New Delhi,2h 40m,Non Stop,"8,223"
1,IndiGo,"Thu, 24 Mar",12:15,09:30,Bangalore,New Delhi,2h 45m,Non Stop,"8,223"
2,SpiceJet,"Thu, 24 Mar",21:50,19:05,Bangalore,New Delhi,2h 45m,Non Stop,"8,223"
3,Air Asia,"Thu, 24 Mar",03:20,00:30,Bangalore,New Delhi,2h 50m,Non Stop,"8,223"
4,IndiGo,"Thu, 24 Mar",09:30,06:40,Bangalore,New Delhi,2h 50m,Non Stop,"8,223"
...,...,...,...,...,...,...,...,...,...
95,Air Asia,,22:55,15:15,Bangalore,New Delhi,7h 40m,1 Stop,"6,963"
96,IndiGo,,23:25,15:35,Bangalore,New Delhi,7h 50m,1 Stop,"6,963"
97,Air India,,00:05\n+ 1 day,21:00,Bangalore,New Delhi,3h 05m,Non Stop,"6,964"
98,Vistara,,23:45,21:10,Bangalore,New Delhi,2h 35m,Non Stop,"7,174"
99,IndiGo,,22:00,19:15,Bangalore,New Delhi,2h 45m,Non Stop,"7,226"

## Chennai - Kolkata

In [251]:
Airline_name = []
Date = []
arrival_time=[]
dep_time = []
source = []
destination=[]
duration = []
total_stops = []
price=[]

In [252]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=CCU&destinationCountry=IN&flexi=0&flight_depart_date=20%2F04%2F2022&hb=0&noOfSegments=1&origin=MAA&originCountry=IN&type=O&unique=1056541118495&version=1.1&viewName=normal')
time.sleep(2)

In [253]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//div/span[@class="i-b text ellipsis"]')
    for i in tag:
        Airline_name.append(i.text)
        
    l1 = len(Airline_name)
    length= l1
except:
    Airline_name.append('Nan')
    
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
except:
    Date.append('Nan')

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')
    
len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25)

In [254]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=CCU&destinationCountry=IN&flexi=0&flight_depart_date=24%2F04%2F2022&hb=0&noOfSegments=1&origin=MAA&originCountry=IN&type=O&unique=1056541118495&version=1.1&viewName=normal')
time.sleep(2)

In [255]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//div/div/div/div[2]/div[1]/div/div[2]/span')
    for i in tag:
        Airline_name.append(i.text)
        
    l2 = len(Airline_name)-l1
    length= l2
except:
    Airline_name.append('Nan')
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
except:
    Date.append('Nan')

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')
    
len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50)

In [256]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=CCU&destinationCountry=IN&flexi=0&flight_depart_date=12%2F04%2F2022&hb=0&noOfSegments=1&origin=MAA&originCountry=IN&type=O&unique=1056541118495&version=1.1&viewName=normal')
time.sleep(2)

In [257]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[1]/div/div[2]/span')
    for i in tag:
        Airline_name.append(i.text)
        
    l3 = len(Airline_name)-l2-l1
    length=l3
except:
    Airline_name.append('Nan')
    
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
        
except:
    pass

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')
    
len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75)

In [258]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=CCU&destinationCountry=IN&flexi=0&flight_depart_date=18%2F04%2F2022&hb=0&noOfSegments=1&origin=MAA&originCountry=IN&type=O&unique=1056541118495&version=1.1&viewName=normal')
time.sleep(2)

In [259]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//span[@class="i-b text ellipsis"]')
    for i in tag:
        Airline_name.append(i.text)
        
    l4 = len(Airline_name)-l2-l1-l3
    length=l4
except:
    Airline_name.append('Nan')
    
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
        
except:
    pass 

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')

len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100)

In [260]:
#loading web driver
driver = webdriver.Chrome(r"C:/Users/atoranga/Documents/chromedriver.exe") 
driver.get('https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=CCU&destinationCountry=IN&flexi=0&flight_depart_date=28%2F04%2F2022&hb=0&noOfSegments=1&origin=MAA&originCountry=IN&type=O&unique=1056541118495&version=1.1&viewName=normal')
time.sleep(2)

In [261]:
#airline tags
try:
    tag = driver.find_elements_by_xpath('//span[@class="i-b text ellipsis"]')
    for i in tag:
        Airline_name.append(i.text)
        
    l5 = len(Airline_name)-l2-l1-l3-l4
    length=l5
except:
    Airline_name.append('Nan')
    
    
#date of journey
try:
    tag = driver.find_elements_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div/p[1]')
    while length>0:
        for i in tag:
            Date.append(i.text)
            length-=1
        
except:
    pass 

#departure time
try:
    tag = driver.find_elements_by_xpath('//div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/div')
    for i in tag:
        dep_time.append(i.text)
except:
    dep_time.append('Nan')

#arrival time
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[1]')
    for i in tag:
        arrival_time.append(i.text)
except:
    arrival_time.append('Nan')


#source
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[1]/p')
    for i in tag:
        source.append(i.text)
except:
    source.append('Nan')
    
#destination
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[1]/div/div[3]/p[2]')
    for i in tag:
        destination.append(i.text)
except:
    destination.append('Nan')    

#total stops
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/span')
    for i in tag:
        total_stops.append(i.text)
except:
    total_stops.append('Nan')

#Price
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[4]/div/div[1]/div/label/div/div[2]')
    for i in tag:
        price.append(i.text)
        
except:
    price.append('Nan')
    
try:
    tag = driver.find_elements_by_xpath('//div/div/div[2]/div[2]/div/div/div/div/div[2]/div/p')
    for i in tag:
        duration.append(i.text)
        
except:
    price.append('Nan')

len(total_stops),len(Airline_name),len(Date),len(arrival_time),len(dep_time),len(dep_time), len(source),len(destination),len(duration),len(total_stops),len(price)

(125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125)

In [262]:
df14 = pd.DataFrame({'Airline Name':Airline_name, 'Departure Date':Date,'Arrival Time':arrival_time,'Departure Time':dep_time, 'Source':source, 'Destination':destination,'Duration':duration,'Total Stops':total_stops,'Price':price})
df14

,Airline Name,Departure Date,Arrival Time,Departure Time,Source,Destination,Duration,Total Stops,Price
0,Go First,,13:30,11:15,Chennai,Kolkata,2h 15m,Non Stop,"5,041"
1,SpiceJet,,14:25,12:10,Chennai,Kolkata,2h 15m,Non Stop,"5,041"
2,SpiceJet,,20:50,18:30,Chennai,Kolkata,2h 20m,Non Stop,"5,041"
3,SpiceJet,,09:15,06:40,Chennai,Kolkata,2h 35m,Non Stop,"5,041"
4,IndiGo,,16:00,13:25,Chennai,Kolkata,2h 35m,Non Stop,"5,042"
...,...,...,...,...,...,...,...,...,...
120,IndiGo,,17:00,10:35,Chennai,Kolkata,6h 25m,1 Stop,"6,775"
121,IndiGo,,14:20,07:45,Chennai,Kolkata,6h 35m,1 Stop,"6,775"
122,IndiGo,,18:00,11:20,Chennai,Kolkata,6h 40m,1 Stop,"6,775"
123,IndiGo,,20:35,13:00,Chennai,Kolkata,7h 35m,1 Stop,"6,775"
124,IndiGo,,16:05,07:45,Chennai,Kolkata,8h 20m,1 Stop,"6,775"

## Let us combine all the dataframes we have scraped into one.

In [263]:
Flight_details = pd.concat((df1,df2,df3,df4,df5,df6,df7,df8,df9,df9,df10,df11,df12,df13,df14), ignore_index=True)
Flight_details

,Airline Name,Departure Date,Arrival Time,Departure Time,Source,Destination,Duration,Total Stops,Price
0,Go First,"Wed, 23 Mar",17:00,15:00,New Delhi,Mumbai,2h 00m,Non Stop,"7,320"
1,Air India,"Wed, 23 Mar",20:00,18:00,New Delhi,Mumbai,2h 00m,Non Stop,"7,320"
2,IndiGo,"Wed, 23 Mar",04:10,02:00,New Delhi,Mumbai,2h 10m,Non Stop,"7,320"
3,Go First,"Wed, 23 Mar",13:25,11:15,New Delhi,Mumbai,2h 10m,Non Stop,"7,320"
4,IndiGo,"Wed, 23 Mar",19:25,17:15,New Delhi,Mumbai,2h 10m,Non Stop,"7,320"
...,...,...,...,...,...,...,...,...,...
1617,IndiGo,,17:00,10:35,Chennai,Kolkata,6h 25m,1 Stop,"6,775"
1618,IndiGo,,14:20,07:45,Chennai,Kolkata,6h 35m,1 Stop,"6,775"
1619,IndiGo,,18:00,11:20,Chennai,Kolkata,6h 40m,1 Stop,"6,775"
1620,IndiGo,,20:35,13:00,Chennai,Kolkata,7h 35m,1 Stop,"6,775"
1621,IndiGo,,16:05,07:45,Chennai,Kolkata,8h 20m,1 Stop,"6,775"

In [264]:
#shuffling all the data and resetting the index

Flight_details = Flight_details.sample(frac=1).reset_index(drop=True)
Flight_details

,Airline Name,Departure Date,Arrival Time,Departure Time,Source,Destination,Duration,Total Stops,Price
0,IndiGo,,13:20,04:30,Ahmedabad,Bangalore,8h 50m,1 Stop,"5,796"
1,Go First,"Wed, 23 Mar",16:05,14:00,New Delhi,Mumbai,2h 05m,Non Stop,"7,320"
2,Air India,,19:15,17:00,Kolkata,Chennai,2h 15m,Non Stop,"8,747"
3,IndiGo,,01:50\n+ 1 day,17:45,Hyderabad,Ahmedabad,8h 05m,1 Stop,"5,750"
4,Air Asia,,23:25,21:00,Kolkata,Chennai,2h 25m,Non Stop,"9,220"
...,...,...,...,...,...,...,...,...,...
1617,Air India,"Wed, 23 Mar",07:05\n+ 1 day,20:10,Kochi,Pune,10h 55m,1 Stop,"28,564"
1618,Vistara,,19:15,17:30,Mumbai,Bangalore,1h 45m,Non Stop,"6,258"
1619,IndiGo,,20:55,15:55,New Delhi,Kolkata,5h 00m,1 Stop,"7,320"
1620,Vistara,"Wed, 23 Mar",07:55,05:45,New Delhi,Mumbai,2h 10m,Non Stop,"7,320"
1621,Air India,,18:20,16:40,Mumbai,Bangalore,1h 40m,Non Stop,"5,103"

In [265]:
# converting the dataframe to csv file

Flight_details.to_csv('Flight_details.csv', index=False)

In [266]:
Flight_details

,Airline Name,Departure Date,Arrival Time,Departure Time,Source,Destination,Duration,Total Stops,Price
0,IndiGo,,13:20,04:30,Ahmedabad,Bangalore,8h 50m,1 Stop,"5,796"
1,Go First,"Wed, 23 Mar",16:05,14:00,New Delhi,Mumbai,2h 05m,Non Stop,"7,320"
2,Air India,,19:15,17:00,Kolkata,Chennai,2h 15m,Non Stop,"8,747"
3,IndiGo,,01:50\n+ 1 day,17:45,Hyderabad,Ahmedabad,8h 05m,1 Stop,"5,750"
4,Air Asia,,23:25,21:00,Kolkata,Chennai,2h 25m,Non Stop,"9,220"
...,...,...,...,...,...,...,...,...,...
1617,Air India,"Wed, 23 Mar",07:05\n+ 1 day,20:10,Kochi,Pune,10h 55m,1 Stop,"28,564"
1618,Vistara,,19:15,17:30,Mumbai,Bangalore,1h 45m,Non Stop,"6,258"
1619,IndiGo,,20:55,15:55,New Delhi,Kolkata,5h 00m,1 Stop,"7,320"
1620,Vistara,"Wed, 23 Mar",07:55,05:45,New Delhi,Mumbai,2h 10m,Non Stop,"7,320"
1621,Air India,,18:20,16:40,Mumbai,Bangalore,1h 40m,Non Stop,"5,103"